version: "3"

networks:
  reverse_proxy:
    external:
      name: "reverse_proxy"
volumes:
  app-volume: 

services:
  recomdation:
    build: ./
    restart: on-failure
    networks:
      - reverse_proxy
    volumes:
      app-volume: /app

  training:
    build:
      context: ./
      dockerfile: Dockerfile.Training
      restart: on-failure
      volumes:
        app-volume: /app


    environment:
      VIRTUAL_HOST: 'recommendation.jobme.teparak.me'
      LETSENCRYPT_HOST: 'recommendation.jobme.teparak.me'
      LETSENCRYPT_EMAIL: 'pan.teparak@gmail.com'
