version: "3"

networks:
  reverse_proxy:
    external:
      name: "reverse_proxy"
volumes:
  app-volume:

services:
  recomdation:
    build: ./
    restart: on-failure
    networks:
      - reverse_proxy
    volumes:
      - app-volume: /app/test_data.csv
      - app-volume: /app/weights.sav
      - app-volume: /app/list_data.sav

  training:
    build:
      context: ./
      dockerfile: Dockerfile.Training
      restart: on-failure
      volumes:
        - app-volume: /app/test_data.csv
        - app-volume: /app/weights.sav
        - app-volume: /app/list_data.sav


    environment:
      VIRTUAL_HOST: 'recommendation.jobme.teparak.me'
      LETSENCRYPT_HOST: 'recommendation.jobme.teparak.me'
      LETSENCRYPT_EMAIL: 'pan.teparak@gmail.com'
